<map id="django.contrib.gis.geos.error.GEOSIndexError" name="django.contrib.gis.geos.error.GEOSIndexError">
<area shape="rect" id="node2" href="$d0/d8c/classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1_g_e_o_s_exception.html" title="django.contrib.gis.geos.error.\lGEOSException" alt="" coords="5,80,196,121"/>
</map>
