<map id="django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_actual_implementation" name="django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_actual_implementation">
<area shape="rect" id="node2" href="$d4/d87/classdjango_1_1utils_1_1unittest_1_1case_1_1_test_case.html#a57a8ee2eb79698b872c1bd173da2c4b8" title="django.utils.unittest.case.\lTestCase.assertIsInstance" alt="" coords="307,57,483,98"/>
<area shape="rect" id="node3" href="$d7/d8d/namespacedjango_1_1utils_1_1unittest_1_1util.html#a5458d1adca8e176eb60d4b1bec27f257" title="django.utils.unittest.util.safe_repr" alt="" coords="531,5,744,32"/>
<area shape="rect" id="node4" href="$d4/d87/classdjango_1_1utils_1_1unittest_1_1case_1_1_test_case.html#a29110c14097b1e7f5377c5b84b856579" title="django.utils.unittest.case.\lTestCase.fail" alt="" coords="552,57,723,98"/>
<area shape="rect" id="node5" href="$d4/d87/classdjango_1_1utils_1_1unittest_1_1case_1_1_test_case.html#a40ccce04668f84595605e9aa450c81f8" title="django.utils.unittest.case.\lTestCase._formatMessage" alt="" coords="549,122,726,163"/>
</map>
