<map id="django.contrib.gis.gdal.error.GDALException" name="django.contrib.gis.gdal.error.GDALException">
</map>
