<map id="django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode" name="django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode">
<area shape="rect" id="node2" href="$d6/d64/namespacedjango_1_1contrib_1_1gis_1_1gdal_1_1prototypes_1_1errcheck.html#af947a6315262cd24865784868e871c12" title="django.contrib.gis.gdal.prototypes.errcheck.arg\l_byref" alt="" coords="364,5,657,47"/>
<area shape="rect" id="node3" href="$d8/d96/namespacedjango_1_1contrib_1_1gis_1_1gdal_1_1error.html#a36fdcad2a8f3ecafb144b30b9eae9424" title="django.contrib.gis.gdal.error.check_err" alt="" coords="389,71,632,98"/>
</map>
