<map id="django.contrib.gis.gdal.error.OGRException" name="django.contrib.gis.gdal.error.OGRException">
<area shape="rect" id="node3" href="$db/d65/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_index_error.html" title="django.contrib.gis.gdal.error.\lOGRIndexError" alt="" coords="5,169,192,211"/>
</map>
