var gdal_2error_8py =
[
    [ "GDALException", "d4/dd5/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_g_d_a_l_exception.html", null ],
    [ "OGRException", "d5/dec/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_exception.html", null ],
    [ "SRSException", "d9/d14/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_s_r_s_exception.html", null ],
    [ "OGRIndexError", "db/d65/classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_o_g_r_index_error.html", null ],
    [ "check_err", "de/de1/gdal_2error_8py.html#a36fdcad2a8f3ecafb144b30b9eae9424", null ],
    [ "OGRERR_DICT", "de/de1/gdal_2error_8py.html#a80558669a349e5e43dd03480789e1071", null ],
    [ "OGRERR_NONE", "de/de1/gdal_2error_8py.html#aeecf8f41c319575bbd31c834204dd254", null ]
];