<map id="django.views.debug.ExceptionReporter.get_traceback_data" name="django.views.debug.ExceptionReporter.get_traceback_data">
<area shape="rect" id="node2" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#abc64451604ad585fdbc69758fd772ea6" title="django.views.debug.Exception\lReporter.get_traceback_html" alt="" coords="249,5,445,47"/>
<area shape="rect" id="node3" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#a4e73474bb71b41a0f90d53345930d4d1" title="django.views.debug.Exception\lReporter.get_traceback_text" alt="" coords="249,71,445,112"/>
</map>
